/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ButtonResponse } from "./ButtonResponse";
import { ButtonResponseCountArgs } from "./ButtonResponseCountArgs";
import { ButtonResponseFindManyArgs } from "./ButtonResponseFindManyArgs";
import { ButtonResponseFindUniqueArgs } from "./ButtonResponseFindUniqueArgs";
import { DeleteButtonResponseArgs } from "./DeleteButtonResponseArgs";
import { ButtonResponseService } from "../buttonResponse.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ButtonResponse)
export class ButtonResponseResolverBase {
  constructor(
    protected readonly service: ButtonResponseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ButtonResponse",
    action: "read",
    possession: "any",
  })
  async _buttonResponsesMeta(
    @graphql.Args() args: ButtonResponseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ButtonResponse])
  @nestAccessControl.UseRoles({
    resource: "ButtonResponse",
    action: "read",
    possession: "any",
  })
  async buttonResponses(
    @graphql.Args() args: ButtonResponseFindManyArgs
  ): Promise<ButtonResponse[]> {
    return this.service.buttonResponses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ButtonResponse, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ButtonResponse",
    action: "read",
    possession: "own",
  })
  async buttonResponse(
    @graphql.Args() args: ButtonResponseFindUniqueArgs
  ): Promise<ButtonResponse | null> {
    const result = await this.service.buttonResponse(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ButtonResponse)
  @nestAccessControl.UseRoles({
    resource: "ButtonResponse",
    action: "delete",
    possession: "any",
  })
  async deleteButtonResponse(
    @graphql.Args() args: DeleteButtonResponseArgs
  ): Promise<ButtonResponse | null> {
    try {
      return await this.service.deleteButtonResponse(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
